### ISSUE TITLE
bad request (400) Cross-origin token redemption not allowed.

### ISSUE THREAD

**Issue by Matix-Media** [Hanro50/MSMC#1]
Hi, so I am trying to integrated MS Login into my launcher. The problem is, that I keep getting an BAD REQUEST (400) error.

Here are my console logs:
```
Update: {type: "Starting"}
Update: {type: "Loading", data: "Getting Login Token", percent: 12.5}
POST https://login.live.com/oauth20_token.srf 400 (Bad Request)
Update: {type: "Loading", data: "Logging into Xbox Live", percent: 25}
POST https://user.auth.xboxlive.com/user/authenticate 400 (Bad Request)
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
```

The response from the first request:
```json
{
"error":"invalid_request",
"error_description":"Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.",
"correlation_id":"31be73ca-b659-4795-....."
}
```

The response from the second request is empty.

I am using electron, and it seems like that this sets the origin to localhost:8080 which is a different port than the web server from the library.

I did change the platform to Mobile and desktop, but the MS error code hints to use Single page application. 
What should I do? Thank you for your help.

**Comment by Hanro50** [comment]
Mmm, what branch are you using?

Nevertheless I'll check my code in the morning since port 8080 was the one I was using in testing so perhaps I just goofed up and didn't notice due to how my testing token is setup specifically.

**Comment by Hanro50** [comment]
After some debugging and private communication on discord. This appears to be an issue with running the library on the front end with "vue-cli-plugin-electron-builder". I do not currently know how exactly to fix this issue since the problem seems to originate from an entry point outside of my control. 

If you experience this bug I recommend either handling the http server call back routing yourself or simply running the library on the back end. 

All around this seems to be an issue with CORS.
