### ISSUE TITLE
TypeError: BrowserWindow is not a constructor

### ISSUE THREAD

**Issue by WorriedArrow** [Hanro50/MSMC#18]
Hi, I'm working on a custom launcher with my friend and was starting to get authentication to work when I found this.
Currently, I'm using MSMC's `fastLaunch` method to open an authentication window. It worked fine with the `raw` framework,
however, when I tried to use `electron` as the framework, I got this error.

### Code: (in renderer.js if that helps!)
```js
msmc.fastLaunch("electron", (update) => {
		//A hook for catching loading bar events and errors, standard with MSMC
		console.log(update);
	})
		.then((result) => {
			//Let's check if we logged in?
			if (msmc.errorCheck(result)) {
				console.log(result.reason);
				return;
			}
			//If the login works
			[Logging code for my console window]
		})
		.catch((reason) => {
			//If the login fails
			console.log("We failed to log someone in because : " + reason);
		});
```

### The error:
```
We failed to log someone in because : TypeError: BrowserWindow is not a constructor [renderer.js:154]
```

**Comment by Hanro50** [comment]
When using electron with Electron you have 3 node contexts. The backend, preloader and the front end. 

MSMC will not work on the front end as the required Electron functions are not exposed in the front-end.

**Comment by Hanro50** [comment]
For more information see the documentation <a href="https://github.com/Hanro50/MSMC#electron">here</a>

**Comment by WorriedArrow** [comment]
Thank you!

**Comment by Hanro50** [comment]
No worries.

**Comment by WorriedArrow** [comment]
Just wondering... is it possible to set the icon of this popup window? I looked in the interface `windowProperties` but I couldn't find anything related to the icon.

**Comment by arduinka55055** [comment]
so how to do "Login with Microsoft" button?
how to link frontend and backend? it is IMPOSSIBLE!

**Comment by Hanro50** [comment]
> so how to do "Login with Microsoft" button? how to link frontend and backend? it is IMPOSSIBLE!

This is beyond the scope of MSMC. Personally I'd recommend trying NW.js since electron needs a lot of boilerplate to send a message between the rendering thread and node thread. 

However, if you insist on using Electron. I can recommend using <a href="https://dev.to/taw/electron-adventures-episode-18-sending-data-to-backend-2nne">this tutorial</a> on how to send data to the backend. You can also see <a href="https://dev.to/taw/electron-adventures-episode-19-sending-data-to-frontend-3kcc"> tutorial</a> about how to send data to the front-end
