### ISSUE TITLE
Bug when executing msmc when running an electron tab

### ISSUE THREAD

**Issue by Happyuky7** [Hanro50/MSMC#39]
**Hello.**

When running msmc inside an electron application it does not work and causes the electron application to produce an error.

This happens when you want to load the **login** or **select_account** page.

**Better explained:** When you create an electron app and place an electron window then when you run for example msmc through a button (In minecraft to start the game for example), this makes the app/page that is loading electron crashes so to speak.

This did not happen in version **4.1.0**, it only happens after update **5.0.0**.

**Comment by Hanro50** [comment]
MSMC does not work on the frontend context in electron. You need to use it on the node context and execute a command over IPC from the front end. 

If you are running the code on the backend already, then I need a crash log to identify what went wrong. Since your explanation doesn't give me a lot to go on.
